name 'biemond-oradb'
version '1.0.8'

author 'Edwin Biemond'
license 'Apache 2.0'
project_page 'https://github.com/biemond/biemond-oradb'
source 'https://github.com/biemond/biemond-oradb'
summary 'Oracle Database 11g / 12 linux / solaris + GoldenGate + RCU installer'
description 'Oracle Database 11g / 12 puppet module, GoldenGate  + RCU installer for SOA Suite, WebCenter and OIM or all'
'Oracle Database 11g / 12 puppet module'
