name 'biemond-oradb'
version '0.8.5'

author 'Edwin Biemond'
license 'Apache 2.0'
project_page 'https://github.com/biemond/puppet/tree/master/modules/oradb'
source 'https://github.com/biemond/puppet/tree/master/modules/oradb'
summary 'Oracle Database 11g / 12 linux'
description 'Oracle Database 11g / 12 puppet module'
'Oracle Database 11g / 12 puppet module'
